{{- $serviceName := include "helm.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  rules:
  {{- range .Values.ingress.host }}
  {{- $url := splitList "/" . }}
  - host: {{ first $url }}
    http:
      paths:
        - path: /{{ rest $url | join "/" }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: 80
  {{- end -}}
  {{- range .Values.ingress.host }}
  {{- $url := splitList "/" . }}
  tls:
  - hosts:
    - {{ first $url }}
    secretName: letsencrypt-secret-hub
  {{- end -}}
